dt1<-read.delim("C:/Users/DELL/Desktop/Coursera/DS Coursera/exdata_data_household_power_consumption/household_power_consumption.txt",sep = ";")
library(dplyr)
dt2<-filter(dt1,(Date=="1/2/2007")|(Date=="2/2/2007"))
datetime<-strptime(paste(dt2$Date," ",dt2$Time),"%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width = 480, height = 480,units="px")
plot(datetime,as.numeric(dt2$Sub_metering_1),type="l",col="black",xlab="",ylab="Energy Sub Metering")
lines(datetime,as.numeric(dt2$Sub_metering_2),col="red")
lines(datetime,as.numeric(dt2$Sub_metering_3),col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1)
dev.off()