dt1<-read.delim("C:/Users/DELL/Desktop/Coursera/DS Coursera/exdata_data_household_power_consumption/household_power_consumption.txt",sep = ";")
library(dplyr)
dt2<-filter(dt1,(Date=="1/2/2007")|(Date=="2/2/2007"))
global_active_power<-as.numeric(dt2$Global_active_power)
png(file="plot1.png",width = 480, height = 480,units="px")
hist(global_active_power,col="red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()